"""Load the models exported by model.ipynb and serve their predictions."""

from dataclasses import dataclass
from math import expm1, isfinite
from pathlib import Path
from typing import Mapping

import joblib
import pandas as pd

ARTIFACT_PATH = Path(__file__).resolve().parent / "artifacts" / "model_bundle.joblib"
FEATURE_STEPS = {
    "fixed acidity": 0.1,
    "volatile acidity": 0.01,
    "citric acid": 0.01,
    "residual sugar": 0.1,
    "chlorides": 0.001,
    "free sulfur dioxide": 1.0,
    "total sulfur dioxide": 1.0,
    "density": 0.00001,
    "pH": 0.01,
    "sulphates": 0.01,
    "alcohol": 0.1,
}
FEATURE_NAMES = tuple(FEATURE_STEPS)
MODEL_NAMES = ("Random Forest", "XGBoost", "LightGBM")


@dataclass(frozen=True)
class FeatureSpec:
    name: str
    minimum: float
    maximum: float
    default: float
    step: float
    display_format: str


@dataclass(frozen=True)
class EvaluationMetrics:
    accuracy: float
    error_rate: float
    within_one_accuracy: float
    mean_absolute_error: float
    weighted_f1: float
    classification_report: tuple[dict[str, float | int], ...]
    quality_scores: tuple[int, ...]
    confusion_matrix: tuple[tuple[int, ...], ...]
    actual_counts: tuple[int, ...]
    predicted_counts: tuple[int, ...]


@dataclass(frozen=True)
class ModelBundle:
    estimator: object
    features: tuple[FeatureSpec, ...]
    metrics: EvaluationMetrics
    train_size: int
    test_size: int
    feature_importances: tuple[float, ...]
    test_actual: tuple[int, ...]
    test_predictions: tuple[float, ...]
    eda_data: pd.DataFrame

    @property
    def feature_names(self) -> tuple[str, ...]:
        return tuple(feature.name for feature in self.features)


@dataclass(frozen=True)
class PredictionResult:
    score: int
    estimated_quality: float
    error_rate: float
    mean_absolute_error: float


def load_models(artifact_path: Path = ARTIFACT_PATH) -> dict[str, ModelBundle]:
    """Read the notebook export; training only happens in model.ipynb."""
    if not artifact_path.is_file():
        raise FileNotFoundError(
            f"Model export not found at {artifact_path}. Run the final cell in model.ipynb."
        )
    export = joblib.load(artifact_path)  # Only load artifacts generated by this project.
    if export.get("version") != 2 or tuple(export["feature_names"]) != FEATURE_NAMES:
        raise ValueError("Model export has an unsupported version or feature schema")
    if set(export["models"]) != set(MODEL_NAMES):
        raise ValueError("Model export must contain exactly the three permitted models")
    features = tuple(FeatureSpec(**item) for item in export["features"])
    eda_data = pd.DataFrame(export["eda_data"])
    test_actual = tuple(int(value) for value in export["test_actual"])
    models = {}
    for name in MODEL_NAMES:
        item = export["models"][name]
        raw = item["metrics"]
        metrics = EvaluationMetrics(
            accuracy=raw["accuracy"],
            error_rate=raw["error_rate"],
            within_one_accuracy=raw["within_one_accuracy"],
            mean_absolute_error=raw["mean_absolute_error"],
            weighted_f1=raw["weighted_f1"],
            classification_report=tuple(raw["classification_report"]),
            quality_scores=tuple(raw["quality_scores"]),
            confusion_matrix=tuple(tuple(row) for row in raw["confusion_matrix"]),
            actual_counts=tuple(raw["actual_counts"]),
            predicted_counts=tuple(raw["predicted_counts"]),
        )
        models[name] = ModelBundle(
            estimator=item["estimator"],
            features=features,
            metrics=metrics,
            train_size=export["train_size"],
            test_size=export["test_size"],
            feature_importances=tuple(item["feature_importances"]),
            test_actual=test_actual,
            test_predictions=tuple(float(value) for value in item["test_predictions"]),
            eda_data=eda_data,
        )
        if len(models[name].test_predictions) != len(test_actual):
            raise ValueError(f"Model export has mismatched test rows for {name}")
    return models


def predict_wine(model: ModelBundle, input_features: Mapping[str, float]) -> PredictionResult:
    """Predict a rounded quality score from the selected notebook regressor."""
    missing = set(model.feature_names) - set(input_features)
    extra = set(input_features) - set(model.feature_names)
    if missing or extra:
        raise ValueError(
            f"Expected exactly the 11 model features (missing: {sorted(missing)}; extra: {sorted(extra)})"
        )
    try:
        values = [float(input_features[name]) for name in model.feature_names]
    except (TypeError, ValueError) as exc:
        raise ValueError("Every feature must be a number") from exc
    if not all(isfinite(value) for value in values):
        raise ValueError("Every feature must be a finite number")
    row = pd.DataFrame([values], columns=model.feature_names)
    original_scale = expm1(float(model.estimator.predict(row)[0]))
    low, high = model.metrics.quality_scores[0], model.metrics.quality_scores[-1]
    return PredictionResult(
        score=max(low, min(high, round(original_scale))),
        estimated_quality=original_scale,
        error_rate=model.metrics.error_rate,
        mean_absolute_error=model.metrics.mean_absolute_error,
    )
