[project]
name = "red-wine-quality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kellygabot", email = "kellygabot3232006@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
red-wine-quality = "red_wine_quality:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
